### ISSUE TITLE
Overall validation

### ISSUE THREAD

**Issue by davide-f** [open-energy-transition/geothermal-modelling#30]
This issue is to track the overall validation needs. It may be moved into mileston [don't have permissions though]

- [ ] Installed capacity #29 
- [ ] Generation #11
       - [ ] Generation mix #9
       - [ ] Generation mix at country level #28
- [ ] Demand
       - [ ] At country level #13 
       - [ ] Generation profile in high resolution #28
- [ ] Network #5

**Comment by ekatef** [comment]
I think we have the right to tick all the boxes here and close the issue :)
